var a=Number(prompt("Enter the first number : "))
var b=Number(prompt("Enter the second number : "))
var c=Number(prompt("Enter the third number : "))
var d=Number(prompt("Enter the forth number : "))
var e=Number(prompt("Enter the fifth number : "))
if(a>=b && a>=c && a>=d && a>=e)
document.write(`${a} is greatest number`)
else if(b>=c && b>=d && b>=e)
document.write(`${b} is greatest number`)
else if(c>=d && c>=e)
document.write(`${c} is greatest number`)
else if(d>=e)
document.write(`${d} is greatest number`)
else
document.write(`${e} is greatest number`)
